const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const auth=tg?.initData||'';let pollTimer=null,selected=[],allRows=[];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>{const headers=new Headers(options.headers||{});headers.set('Authorization',`tma ${auth}`);const r=await fetch(`/miniapp/api${path}`,{...options,headers});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.detail||'Не удалось выполнить запрос')}return r.json()};
const labels={queued:'В очереди',processing:'Анализ',completed:'Готово',failed:'Ошибка',rejected:'Отклонено'};
const jumpNames={axel:'Аксель',loop:'Риттбергер',salchow:'Сальхов',flip:'Флип',lutz:'Лутц',toe_loop:'Тулуп',floor_tour:'Тур в зале',countermovement:'Без классификации'};
const rotations={1:'Одинарный',2:'Двойной',3:'Тройной',4:'Четверной'};
const quality={low_fps:'Низкая частота кадров',low_landmark_visibility:'Часть тела распознана неуверенно',interpolated_pose_gap:'Короткое перекрытие восстановлено',partial_com_fallback:'Центр масс оценён приближённо',ankle_based_ground_contact:'Контакт оценён по лодыжкам',unstable_trunk_orientation:'Вращение определено неуверенно',implausible_rotation_speed:'Возможен скачок распознавания',inconsistent_height_estimates:'Оценки высоты расходятся'};
const coachingSignals={possible_lower_jump_height:'Высота ниже личной медианы',possible_shorter_flight:'Время полёта короче обычного',possible_slower_rotation:'Вращение медленнее личной медианы'};
function jumpLabel(jump){if(jump.metric_data?.declared_jump_label)return jump.metric_data.declared_jump_label;const type=jump.jump_type,match=/^([1-4])_(.+)$/.exec(type||'');return match?`${rotations[match[1]]} ${jumpNames[match[2]]||match[2]}`:jumpNames[type]||'Без классификации'}
function height(j){return Number(j.metric_data?.height_ballistic_m??(j.height_flight_cm?Number(j.height_flight_cm)/100:null))*100}
function coaching(j){const a=j.metric_data?.technique_assessment,p=j.metric_data?.personal_comparison,parts=[];if(a?.status==='possible_rotation_deficit')parts.push('Возможен дефицит вращения по 2D');if(a?.status==='within_2d_tolerance')parts.push('Вращение в пределах 2D-допуска');for(const s of p?.signals||[])parts.push(coachingSignals[s]||s);return parts.length?`<div class="warnings coaching">${parts.map(esc).join(' · ')}</div>`:''}
function visibleRows(){const value=$('jump-filter').value;return value==='all'?allRows:allRows.filter(j=>j.jump_type===value)}
function render(rows){const done=rows.filter(j=>j.status==='completed'&&Number.isFinite(height(j))).slice(0,8).reverse(),max=Math.max(...done.map(height),1);$('trend').classList.toggle('hidden',!done.length);$('trend').innerHTML=done.map(j=>`<div class="bar"><strong>${height(j).toFixed(1)}</strong><i style="height:${Math.max(8,height(j)/max*100)}px"></i><span>${new Date(j.created_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})}</span></div>`).join('');$('history').innerHTML=rows.length?rows.map(j=>{const h=height(j),conf=Math.round(Number(j.confidence_score||0)*100),flags=j.quality_flags||[],velocity=j.takeoff_velocity_mps?Number(j.takeoff_velocity_mps).toFixed(2):'—',rotation=j.max_angular_velocity_dps?Math.round(Number(j.max_angular_velocity_dps)):'—';return `<article class="card ${selected.some(x=>x.id===j.id)?'selected':''}" data-id="${j.id}"><div class="card-top"><span class="status">${labels[j.status]||j.status}</span><small>${new Date(j.created_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</small></div><span class="jump-name">${esc(jumpLabel(j))}</span><div class="metric">${Number.isFinite(h)?h.toFixed(1):'—'} <small>см</small></div><small>Высота по полёту</small>${j.status==='completed'?`<div class="details">Взлёт: <b>${velocity} м/с</b><br>Вращение: <b>${rotation} °/с</b></div><div class="confidence"><span>Confidence</span><strong>${conf}%</strong></div><div class="mini-track"><i style="width:${conf}%"></i></div>`:''}${flags.length?`<div class="warnings">${flags.slice(0,2).map(f=>esc(quality[f]||f)).join(' · ')}</div>`:''}${coaching(j)}${j.error_message?`<div class="warnings">${esc(j.error_message)}</div>`:''}</article>`}).join(''):'<div class="empty">Для этого элемента попыток пока нет.</div>';document.querySelectorAll('.card').forEach(el=>el.onclick=()=>toggle(rows.find(x=>x.id===el.dataset.id),rows));const active=rows.find(j=>['queued','processing'].includes(j.status));if(active&&!pollTimer)pollTimer=setTimeout(()=>{pollTimer=null;load()},2500)}
function toggle(j,rows){if(!j||j.status!=='completed')return;const i=selected.findIndex(x=>x.id===j.id);if(i>=0)selected.splice(i,1);else{if(selected.length&&selected[0].jump_type!==j.jump_type)selected=[];selected.push(j);if(selected.length>2)selected.shift()}render(rows);renderCompare()}
function renderCompare(){const box=$('comparison');if(selected.length!==2){box.classList.add('hidden');return}const [a,b]=selected,ha=height(a),hb=height(b),delta=hb-ha;box.classList.remove('hidden');$('compare-body').innerHTML=`<p class="jump-name">${esc(jumpLabel(a))}</p><div class="compare-grid"><div class="compare-value">${ha.toFixed(1)} см<br><small>${new Date(a.created_at).toLocaleDateString('ru-RU')}</small></div><span class="delta">${delta>=0?'+':''}${delta.toFixed(1)} см</span><div class="compare-value">${hb.toFixed(1)} см<br><small>${new Date(b.created_at).toLocaleDateString('ru-RU')}</small></div></div>`}
function updateFilter(){const filter=$('jump-filter'),current=filter.value,rowsByType=new Map(allRows.map(j=>[j.jump_type,j])),types=[...rowsByType.keys()];filter.innerHTML='<option value="all">Все прыжки</option>'+types.map(t=>`<option value="${esc(t)}">${esc(jumpLabel(rowsByType.get(t)))}</option>`).join('');filter.value=types.includes(current)?current:'all'}
async function load(){if(!auth){$('error').textContent='Откройте приложение из Telegram — браузерный вход не подтверждён.';$('error').classList.remove('hidden');return}try{const [me,rows]=await Promise.all([api('/me'),api('/analyses')]);allRows=rows;$('avatar').textContent=(me.first_name||'JH').slice(0,2).toUpperCase();updateFilter();render(visibleRows())}catch(e){$('error').textContent=e.message;$('error').classList.remove('hidden')}}
$('jump-filter').onchange=()=>{selected=[];renderCompare();render(visibleRows())};$('video').onchange=e=>$('file-label').textContent=e.target.files[0]?.name||'Выбрать видео';$('refresh').onclick=load;
document.querySelectorAll('input[name="analysis_mode"]').forEach(input=>input.onchange=e=>{const cascade=e.target.value==='cascade';$('cascade-count-field').hidden=!cascade;const select=$('cascade-count-field').querySelector('select');select.disabled=!cascade});
$('upload-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),xhr=new XMLHttpRequest(),p=$('progress');p.classList.remove('hidden');$('error').classList.add('hidden');xhr.open('POST','/miniapp/api/analyses');xhr.setRequestHeader('Authorization',`tma ${auth}`);xhr.upload.onprogress=x=>{const n=x.lengthComputable?Math.round(x.loaded/x.total*100):15;$('progress-bar').style.width=`${n}%`;$('progress-value').textContent=`${n}%`};xhr.onload=()=>{if(xhr.status===202){$('progress-title').textContent='Видео в очереди';$('progress-note').textContent='Статус обновится автоматически';e.target.reset();$('file-label').textContent='Выбрать видео';load()}else{let d={};try{d=JSON.parse(xhr.responseText)}catch{}$('error').textContent=d.detail||'Загрузка не удалась';$('error').classList.remove('hidden');p.classList.add('hidden')}};xhr.onerror=()=>{$('error').textContent='Сеть недоступна';$('error').classList.remove('hidden');p.classList.add('hidden')};xhr.send(form)};
load();
